=== MarkoOtlokan/Uvod-u-medicinsku-informatiku-Projektni-zadatak-2017-2018./patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="patiente">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="patient" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="2"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="surname">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="2"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="date_of_birth">
								<xs:simpleType>
									<xs:restriction base="xs:date">
										<xs:minInclusive value="1900-01-01"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="LBO" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="\d{11}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MarkoOtlokan/Uvod-u-medicinsku-informatiku-Projektni-zadatak-2017-2018./Patient.xml
<?xml version='1.0' encoding='UTF-8'?>
<patiente xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="patient.xsd">
  <patient LBO="12312312312">
    <name>sdfsara</name>
    <surname>Niddddc</surname>
    <date_of_birth>2001</date_of_birth>
  </patient>
  <patient LBO="12345678912">
    <name>Sara</name>
    <surname>Nikolic</surname>
    <date_of_birth>2000</date_of_birth>
  </patient>
</patiente>
